version: '3.7'

services:
  db:
    container_name: database
    image: postgres:9.6.17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: web
    command: daphne filesharing.asgi:application
    volumes:
      - .:/filesharing
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - redis:redis
  celery:
    build: .
    command: celery -A filesharing worker -l info
    volumes:
      - .:/filesharing
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A filesharing beat --pidfile= -l info
    volumes:
      - .:/filesaring
    depends_on:
      - db
      - redis
      - web
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data: {}
  static: {}
  media: {}
